### ISSUE TITLE
Don't work after Tera Eu patch and proxy Update

### ISSUE THREAD

**Issue by rxghost92** [eemj/free-ghillieglade-tp#1]
Hi today Tera Eu got a new patch and after updated tera proxy pinkie (and removed 2 lines), proxy don't work, after i wrote "/proxy ghill" nothing happen.

**Comment by Activeo2o** [comment]
Hopefully he's going to update it quickly :p

**Comment by eemj** [comment]
Thank you for letting me know, should be working now if you follow the new instructions.
