### ISSUE TITLE
OP Code

### ISSUE THREAD

**Issue by Sternachen** [eemj/free-ghillieglade-tp#2]
OP code not longer valid with new EU patch, would find it by myself but idk what tirggers the C_REQUEST_TELEPORT

**Comment by eemj** [comment]
Pardon me for the late reply, I'm working on it (should be updated in a few minutes).

**Comment by ScriptSK** [comment]
thx for OP code but it dosent work

**Comment by eemj** [comment]
are you using Pinkie's latest proxy? I guess I'll have to push the new updates.
