### ISSUE TITLE
Second teleport issue

### ISSUE THREAD

**Issue by danny961789** [eemj/free-ghillieglade-tp#3]
After logging in first use is going fine. I do the dungeon and reset.
If I try to teleport 2nd time without relogging first I get something similar to disconnect.
I see other users moving but I cannot do anything like teleporting anywhere using skills or even moving (my character only moves client-side)

**Comment by eemj** [comment]
Thanks for letting me know, it should be fixed now.

**Comment by ScriptSK** [comment]
Thx work like charm ;)
PS: please can you explaine to me. whats wrong withe pinky proxy (i've made the def for the req_tp and updated map with your op) but the dispatsh to server doesnt work

**Comment by eemj** [comment]
Pinkie basically created multiple blobs in his proxy to block every ``dispatch.toServer('C_REQUEST_TELEPORT', ...<something something>)`` request, there are two ways you can make it work again, either reverse engineer his blobs and find out what's it's checking and remove it, or you could do it the lazy way like I did with this script and just send a buffer to the server.

**Comment by ScriptSK** [comment]
thx for your your clear and fast answer.
so if the triger is  "dispatch.toServer('C_REQUEST_TELEPORT' ...." .Changing the .def name should solve the problem also :D

**Comment by eemj** [comment]
That's true, then it just depends on what you're sending through buffer, and if the renamed .def file is mapped in your protocol maps.
