### ISSUE TITLE
Module isnt working

### ISSUE THREAD

**Issue by DemonBladek** [eemj/free-ghillieglade-tp#5]
Hi, my proxy loads the module without any problem. Nevertheless, the command to tp doesn´t seem to work. I don't get any error in the console so it's odd. Do you recommend a certain proxy or do I need to do anything else to make this module work?
Thanks ahead

**Comment by eemj** [comment]
I last tested it on Pinkie's latest proxy and it was working, make sure your opcode is set to the region you're playing on.

**Comment by DemonBladek** [comment]
is there any updated tutorial about running his proxy? Because it's not explained and I always get an error when I run the .bat launcher. I may be using an old version idk

**Comment by FoxPride** [comment]
https://docs.google.com/document/d/1bNe06tmDHtOVV0gNM3naHx6MBWWVyg7AW--y5mrCWzI/edit 
Check this set-up guide for Proxy, DemonBladek.

**Comment by DemonBladek** [comment]
Thank you so much. It's already working. 
I just wonder: Is this module detectable? Do they have any way to detect someone using it if he has not been reported?

**Comment by eemj** [comment]
Yes it is detectable, they could check your logs like for example if you bought the scroll and if you used the scroll before teleportation..but I've been using it for over 8 months now and I'm still not banned. Just make sure you don't trigger the teleport near a lot of people you should go someplace where you're sure you're alone.
